# Generated by Django 4.1.1 on 2022-09-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=255)),
                ('commentaire', models.CharField(max_length=255)),
                ('annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiplomeObtenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
                ('telLieuDip', models.CharField(max_length=255)),
                ('diplome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.diplome')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('emailPro', models.CharField(max_length=255)),
                ('nomEntreprise', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('effectif', models.IntegerField()),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GrilleSalariale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=255)),
                ('tauxHoraire', models.IntegerField()),
                ('tauxMensuel', models.IntegerField()),
                ('pause', models.IntegerField()),
                ('salaireDeBase', models.IntegerField()),
                ('primeLogement', models.IntegerField()),
                ('primeTransport', models.IntegerField()),
                ('primeAncien', models.IntegerField()),
                ('indenminite', models.IntegerField()),
                ('avantageNature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoyenDePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SituationMatrimoniale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(max_length=255)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('nationalite', models.CharField(max_length=255)),
                ('motDePasse', models.CharField(max_length=255)),
                ('annonces', models.ManyToManyField(through='oju.Avis', to='oju.annonce')),
                ('diplomes', models.ManyToManyField(through='oju.DiplomeObtenu', to='oju.diplome')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oju.utilisateur')),
                ('adresse', models.CharField(max_length=255)),
                ('numero_cnss', models.CharField(max_length=255)),
                ('nombre_enfant', models.IntegerField()),
                ('dateEmbauche', models.DateField()),
                ('congeConsomme', models.IntegerField()),
                ('superviseur', models.CharField(max_length=255)),
                ('personneUrgence', models.CharField(max_length=255)),
                ('telephoneUrgence', models.IntegerField()),
                ('photo', models.FileField(upload_to='photos')),
                ('moyenDePaiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.moyendepaiement')),
            ],
            bases=('oju.utilisateur',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('grilleSalariale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.grillesalariale')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.service')),
                ('typeContrat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.typecontrat')),
            ],
        ),
        migrations.CreateModel(
            name='Duree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutContrat', models.DateField()),
                ('dateFinContrat', models.DateField()),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.poste')),
            ],
        ),
        migrations.AddField(
            model_name='diplomeobtenu',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.utilisateur'),
        ),
        migrations.AddField(
            model_name='avis',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.utilisateur'),
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField()),
                ('date', models.DateField()),
                ('montantRetire', models.IntegerField()),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.employe')),
            ],
        ),
        migrations.CreateModel(
            name='HeureSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heureSupplementaireJour', models.IntegerField()),
                ('heureSupplementaireNuit', models.IntegerField()),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.employe')),
            ],
        ),
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutPeriode', models.DateField()),
                ('dateFinPeriode', models.DateField()),
                ('datePaiement', models.DateField()),
                ('nombreDeJourTravaille', models.IntegerField()),
                ('numeroSecuriteSociale', models.CharField(max_length=255)),
                ('entrepriseUtilisatrice', models.CharField(max_length=255)),
                ('salaireBrut', models.IntegerField()),
                ('brutImposable', models.IntegerField()),
                ('brutArrondi', models.IntegerField()),
                ('cnss', models.IntegerField()),
                ('ipts', models.IntegerField()),
                ('totalDeduction', models.IntegerField()),
                ('salaireNet', models.IntegerField()),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='postes',
            field=models.ManyToManyField(through='oju.Duree', to='oju.poste'),
        ),
        migrations.AddField(
            model_name='employe',
            name='situationMatrimoniale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.situationmatrimoniale'),
        ),
        migrations.AddField(
            model_name='duree',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.employe'),
        ),
        migrations.CreateModel(
            name='DossierFamiliaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acteNaissanceEnfant', models.FileField(upload_to='fichiers')),
                ('acteNaissanceConjointe', models.FileField(upload_to='fichiers')),
                ('acteMariage', models.FileField(upload_to='fichiers')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('estTraite', models.BooleanField()),
                ('date', models.DateField()),
                ('motif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.motif')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oju.employe')),
            ],
        ),
    ]
