# Generated by Django 4.1.1 on 2022-09-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oju', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='superviseur',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
