# Generated by Django 4.0.6 on 2022-10-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oju', '0002_alter_employe_superviseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichedepaie',
            name='entrepriseUtilisatrice',
        ),
        migrations.RemoveField(
            model_name='fichedepaie',
            name='numeroSecuriteSociale',
        ),
    ]
