# Generated by Django 4.0.6 on 2022-10-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oju', '0003_remove_fichedepaie_entrepriseutilisatrice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichedepaie',
            name='totalDeduction',
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='accompte',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='deductionFacultative',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='deductionObligatoire',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='oppositionSaisie',
            field=models.IntegerField(null=True),
        ),
    ]
