# Generated by Django 4.0.6 on 2022-10-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oju', '0004_remove_fichedepaie_totaldeduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichedepaie',
            name='datePaiement',
            field=models.DateField(null=True),
        ),
    ]
